name: MagicHopper
main: io.siggi.magichopper.MagicHopper
version: ${project.version}
author: Siggi
description: MagicHopper filter plugin.
api-version: 1.13
permissions:
  magichopper.use:
    description: The ability to use MagicHopper.
    default: op
  magichopper.type.allow:
    description: The ability to use the allow filter.
    default: op
  magichopper.type.block:
    description: The ability to use the block filter.
    default: op
  magichopper.type.compact:
    description: The ability to use the compact filter.
    default: op
  magichopper.type.count:
    description: The ability to use the counter.
    default: op
  magichopper.type.duplicate:
    description: The ability to make a hopper an item duplicator.
    default: op
  magichopper.type.matchfurnace:
    description: The ability to use the match furnace filter.
    default: op
  magichopper.type.skip:
    description: The ability to use the skip filter.
    default: op
  magichopper.type.autodrop:
    description: The ability to make droppers auto drop items when they receive them.
    default: op
  magichopper.type.standard:
    description: All standard filters except for duplicate.
    default: op
    children:
      magichopper.type.allow: true
      magichopper.type.block: true
      magichopper.type.compact: true
      magichopper.type.count: true
      magichopper.type.matchfurnace: true
      magichopper.type.skip: true
      magichopper.type.autodrop: true
